Revert "Upgrade infra-packages"
Ref #2037

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
    model = yield maybe_future(
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "/opt/conda/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 184, in start_kernel
    km, kernel_name, kernel_id = self.pre_start_kernel(kernel_name, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 169, in pre_start_kernel
    km = self.kernel_manager_factory(connection_file=os.path.join(
  File "/opt/conda/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 83, in create_kernel_manager
    km = kernel_manager_ctor(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/configurable.py", line 82, in __init__
    super(Configurable, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1080, in __init__
    super_kwargs[key] = value
  File "/opt/conda/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1214, in hold_trait_notifications
    self.notify_change(change)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1227, in notify_change
    return self._notify_observers(change)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
    c(event)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 888, in compatible_observer
    return func(self, change)
TypeError: _kernel_spec_manager_changed() takes 1 positional argument but 2 were given

```
This reverts commit fdbb535d867dd08b811ddedc27079ca55289b5a5.